name: Deploy Azure Functions App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: func-adnocgpt    # set this to your function app name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'               # set this to the path to your function app project
  PYTHON_VERSION: '3.11'                            # set this to the Python version your function app uses

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: func-adnocgpt
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Resolve dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-azurepipelines

    - name: Run tests (optional)
      run: |
        # Add your test commands here
        # pytest

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        # If using Azure RBAC authentication instead of publish profile:
        # scm-do-build-during-deployment: true
        # enable-oryx-build: true
        # Uncomment the following if you're using Azure RBAC authentication
        # creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
